// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Immortal_sw from "./routes/Immortal/sw.js";
import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_also_wasm_ from "./routes/api/[also]/[wasm].ts";
import * as $api_wasm_ from "./routes/api/[wasm].ts";
import * as $api_create_file_by_size from "./routes/api/create-file-by-size.ts";
import * as $api_jokeSql from "./routes/api/jokeSql.ts";
import * as $api_jokeTxt from "./routes/api/jokeTxt.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $map from "./routes/map.tsx";
import * as $wasm_hello from "./routes/wasm_hello.ts";
import * as $wasm_stress from "./routes/wasm_stress.ts";
import * as $Counter from "./islands/Counter.tsx";
import * as $MapIsland from "./islands/MapIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Immortal/sw.js": $Immortal_sw,
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/api/[also]/[wasm].ts": $api_also_wasm_,
    "./routes/api/[wasm].ts": $api_wasm_,
    "./routes/api/create-file-by-size.ts": $api_create_file_by_size,
    "./routes/api/jokeSql.ts": $api_jokeSql,
    "./routes/api/jokeTxt.ts": $api_jokeTxt,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/map.tsx": $map,
    "./routes/wasm_hello.ts": $wasm_hello,
    "./routes/wasm_stress.ts": $wasm_stress,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MapIsland.tsx": $MapIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
